import React, { useEffect, useMemo, useRef, useState } from 'react';
import {
  StyleSheet,
  View,
  Text,
  TextInput,
  TouchableOpacity,
  Image,
  ScrollView,
  SafeAreaView,
  StatusBar,
  KeyboardAvoidingView,
  Platform,
  Modal,
  Pressable,
  Animated,
  Easing,
  Dimensions,
  FlatList,
} from 'react-native';
import { Ionicons, FontAwesome5, Octicons, Feather } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import BackButton from '../../components/BackButton';
import AnimatedAuroraBackground from '../../components/AnimatedAuroraBackground';
import LoadingButton from '../../components/LoadingButton';
import { useAppAlert } from '../../components/AppAlert';
import { sendSignupOtp } from '../../services/api';
import { COUNTRIES, countryFlag, type Country } from '../../services/currency';

import { friendlyError } from '../../services/errors';
const { height: SCREEN_HEIGHT } = Dimensions.get('window');

const TERMS_UPDATED = 'September 2026';

const TERMS_SECTIONS: { title: string; body: string }[] = [
  {
    title: '1. Accepting these terms',
    body: 'By creating an Apsuni AI account you agree to these Terms and Conditions and our Privacy Policy. If you do not agree, do not create an account or use the app.',
  },
  {
    title: '2. Your account',
    body: 'You must give accurate details, including your name, email, phone number and country, and keep them up to date. You are responsible for keeping your password safe and for everything done through your account.',
  },
  {
    title: '3. Wallets and payments',
    body: 'Wallet top-ups are processed by our payment partner, Flutterwave. Amounts are shown in the currency of the country you choose. Funds added to a wallet are used to pay for products and services on Apsuni and are not a bank deposit.',
  },
  {
    title: '4. Products, templates and AI content',
    body: 'Templates, designs and business guides generated by Apsuni AI are provided as-is for guidance. You are responsible for checking that they suit your needs and comply with the laws where you operate.',
  },
  {
    title: '5. Acceptable use',
    body: 'Do not use Apsuni to break the law, infringe anyone’s rights, upload harmful content, or attempt to access other users’ accounts or our systems without permission.',
  },
  {
    title: '6. Privacy',
    body: 'We collect the information needed to run your account, process payments and improve the service. We do not sell your personal data. See the Privacy Policy for details on how your data is used and stored.',
  },
  {
    title: '7. Suspension and closing your account',
    body: 'We may suspend accounts that break these terms. You can deactivate your account at any time from your profile settings.',
  },
  {
    title: '8. Changes to these terms',
    body: 'We may update these terms from time to time. We will let you know about important changes, and continuing to use the app means you accept the updated terms.',
  },
];

/** Bottom sheet shell shared by the country picker and the terms popup. */
function Sheet({ visible, onClose, children, height }: { visible: boolean; onClose: () => void; children: React.ReactNode; height: number }) {
  const [mounted, setMounted] = useState(visible);
  const translate = useRef(new Animated.Value(SCREEN_HEIGHT)).current;
  const fade = useRef(new Animated.Value(0)).current;

  useEffect(() => {
    if (visible) {
      setMounted(true);
      Animated.parallel([
        Animated.timing(fade, { toValue: 1, duration: 220, useNativeDriver: true }),
        Animated.spring(translate, { toValue: 0, friction: 10, tension: 70, useNativeDriver: true }),
      ]).start();
      return;
    }
    Animated.parallel([
      Animated.timing(fade, { toValue: 0, duration: 180, useNativeDriver: true }),
      Animated.timing(translate, { toValue: SCREEN_HEIGHT, duration: 240, easing: Easing.in(Easing.cubic), useNativeDriver: true }),
    ]).start(({ finished }) => { if (finished) setMounted(false); });
  }, [visible, fade, translate]);

  if (!mounted) return null;

  return (
    <Modal visible transparent statusBarTranslucent animationType="none" onRequestClose={onClose}>
      <View style={styles.sheetRoot}>
        <Animated.View style={[styles.sheetBackdrop, { opacity: fade }]}>
          <Pressable style={StyleSheet.absoluteFill} onPress={onClose} />
        </Animated.View>
        <Animated.View style={[styles.sheet, { height, transform: [{ translateY: translate }] }]}>
          <View style={styles.sheetHandle} />
          {children}
        </Animated.View>
      </View>
    </Modal>
  );
}

export default function SignUpScreen() {
  const router = useRouter();
  const [fullName, setFullName] = useState('');
  const [email, setEmail] = useState('');
  const [phone, setPhone] = useState('');
  const [country, setCountry] = useState<Country | null>(null);
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [agree, setAgree] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [countryPickerVisible, setCountryPickerVisible] = useState(false);
  const [countryQuery, setCountryQuery] = useState('');
  const [termsVisible, setTermsVisible] = useState(false);
  const [termsRead, setTermsRead] = useState(false);
  const agreeShake = useRef(new Animated.Value(0)).current;
  const { showAlert } = useAppAlert();

  const filteredCountries = useMemo(() => {
    const query = countryQuery.trim().toLowerCase();
    if (!query) return COUNTRIES;
    return COUNTRIES.filter((item) =>
      item.name.toLowerCase().includes(query) || item.code.toLowerCase() === query || item.currency.toLowerCase().includes(query));
  }, [countryQuery]);

  const shakeAgree = () => {
    agreeShake.setValue(0);
    Animated.sequence([
      Animated.timing(agreeShake, { toValue: 1, duration: 60, useNativeDriver: true }),
      Animated.timing(agreeShake, { toValue: -1, duration: 60, useNativeDriver: true }),
      Animated.timing(agreeShake, { toValue: 1, duration: 60, useNativeDriver: true }),
      Animated.timing(agreeShake, { toValue: 0, duration: 60, useNativeDriver: true }),
    ]).start();
  };

  const handleSignUp = async () => {
    if (!fullName.trim() || !email.trim() || !phone.trim() || !password) {
      showAlert('Complete your name, email, phone number, and password first.');
      return;
    }
    if (!country) {
      showAlert({ title: 'Country required', message: 'Select your country. We use it to show prices in your currency.' });
      return;
    }
    if (!agree) {
      shakeAgree();
      showAlert({ title: 'Accept the terms', message: 'You need to accept the Terms and Conditions before you can create an account.' });
      return;
    }
    setIsSubmitting(true);
    try {
      await sendSignupOtp(email.trim());
      router.push({
        pathname: '/Screen/Auth/OtpVerificationScreen',
        params: { email: email.trim(), fullName: fullName.trim(), phone: phone.trim(), password, country: country.code, acceptedTerms: 'true' },
      });
    } catch (requestError) {
      showAlert({ title: 'Sign up failed', message: friendlyError(requestError, 'Unable to send the verification code.') });
    } finally {
      setIsSubmitting(false);
    }
  };

  const openCountryPicker = () => {
    setCountryQuery('');
    setCountryPickerVisible(true);
  };

  const openTerms = () => {
    setTermsRead(false);
    setTermsVisible(true);
  };

  const acceptTerms = () => {
    setAgree(true);
    setTermsVisible(false);
  };

  const declineTerms = () => {
    setAgree(false);
    setTermsVisible(false);
  };

  const toggleAgree = () => {
    // Ticking the box for the first time opens the terms so they are actually seen.
    if (!agree) openTerms();
    else setAgree(false);
  };

  return (
    <View style={styles.background}>
      <AnimatedAuroraBackground />
      <SafeAreaView style={{ flex: 1 }}>
        <StatusBar barStyle="light-content" />
        <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : 'height'} style={{ flex: 1 }}>
          <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled">
            {/* Header */}
            <View style={styles.header}>
              <BackButton />
              <View style={{ width: 36 }} />
            </View>

            {/* Logo */}
            <View style={styles.logoRow}>
              <View style={styles.logoMark}><Image source={require('../../../assets/images/AL3.png')} style={styles.logoImage} resizeMode="contain" /></View>
              <Text style={styles.logoText}>Apsuni</Text>
            </View>

            <Text style={styles.title}>Create Account</Text>
            <Text style={styles.subtitle}>
              Join the future with AI-driven.
            </Text>

            {/* Bordered form panel */}
            <View style={styles.formCard}>
              {/* Social Logins */}
              <View style={styles.socialRow}>
                <TouchableOpacity style={[styles.socialPill, styles.socialDisabled]} activeOpacity={1} disabled accessibilityState={{ disabled: true }}>
                  <FontAwesome5 name="google" size={16} color="#FFFFFF" />
                  <Text style={styles.socialText}>Google</Text>
                </TouchableOpacity>
                <TouchableOpacity style={[styles.socialPill, styles.socialDisabled]} activeOpacity={1} disabled accessibilityState={{ disabled: true }}>
                  <FontAwesome5 name="apple" size={18} color="#FFFFFF" />
                  <Text style={styles.socialText}>Apple</Text>
                </TouchableOpacity>
              </View>

              {/* Divider */}
              <View style={styles.dividerRow}>
                <View style={styles.dividerLine} />
                <Text style={styles.dividerLabel}>Or sign up with</Text>
                <View style={styles.dividerLine} />
              </View>

              {/* Full Name */}
              <Text style={styles.fieldLabel}>Full Name</Text>
              <View style={styles.inputWrapper}>
                <Ionicons name="person-outline" size={18} color="#94A3B8" style={styles.fieldIcon} />
                <TextInput
                  style={styles.input}
                  placeholder="Enter your full name"
                  placeholderTextColor="#64748B"
                  value={fullName}
                  onChangeText={setFullName}
                />
              </View>

              {/* Email */}
              <Text style={styles.fieldLabel}>Email</Text>
              <View style={styles.inputWrapper}>
                <Ionicons name="mail-outline" size={18} color="#94A3B8" style={styles.fieldIcon} />
                <TextInput
                  style={styles.input}
                  placeholder="Enter your email"
                  placeholderTextColor="#64748B"
                  value={email}
                  onChangeText={setEmail}
                  keyboardType="email-address"
                  autoCapitalize="none"
                />
              </View>

              {/* Phone */}
              <Text style={styles.fieldLabel}>Phone Number</Text>
              <View style={styles.inputWrapper}>
                <Ionicons name="call-outline" size={18} color="#94A3B8" style={styles.fieldIcon} />
                <TextInput
                  style={styles.input}
                  placeholder="Enter your phone number"
                  placeholderTextColor="#64748B"
                  value={phone}
                  onChangeText={setPhone}
                  keyboardType="phone-pad"
                  autoComplete="tel"
                  textContentType="telephoneNumber"
                />
              </View>

              {/* Country */}
              <View style={styles.labelRow}>
                <Text style={styles.fieldLabel}>Country</Text>
                <Text style={styles.requiredMark}>Required</Text>
              </View>
              <TouchableOpacity style={styles.inputWrapper} activeOpacity={0.8} onPress={openCountryPicker} accessibilityRole="button" accessibilityLabel="Select your country">
                {country ? (
                  <Text style={styles.flag}>{countryFlag(country.code)}</Text>
                ) : (
                  <Ionicons name="globe-outline" size={18} color="#94A3B8" style={styles.fieldIcon} />
                )}
                <Text style={[styles.input, !country && styles.placeholderText]} numberOfLines={1}>
                  {country ? country.name : 'Select your country'}
                </Text>
                {country && (
                  <View style={styles.currencyPill}>
                    <Text style={styles.currencyPillText}>{country.symbol} {country.currency}</Text>
                  </View>
                )}
                <Feather name="chevron-down" size={18} color="#94A3B8" />
              </TouchableOpacity>
              {country && <Text style={styles.fieldHint}>Prices in the app will show in {country.currency} ({country.symbol}).</Text>}

              {/* Password */}
              <Text style={styles.fieldLabel}>Password</Text>
              <View style={styles.inputWrapper}>
                <Octicons name="key" size={18} color="#94A3B8" style={styles.fieldIcon} />
                <TextInput
                  style={styles.input}
                  placeholder="Enter your password"
                  placeholderTextColor="#64748B"
                  value={password}
                  onChangeText={setPassword}
                  secureTextEntry={!showPassword}
                />
                <TouchableOpacity onPress={() => setShowPassword(!showPassword)}>
                  <Ionicons name={showPassword ? 'eye-outline' : 'eye-off-outline'} size={18} color="#94A3B8" />
                </TouchableOpacity>
              </View>

              {/* Terms */}
              <Animated.View style={{ transform: [{ translateX: agreeShake.interpolate({ inputRange: [-1, 1], outputRange: [-8, 8] }) }] }}>
                <View style={styles.agreeRow}>
                  <TouchableOpacity onPress={toggleAgree} activeOpacity={0.7} accessibilityRole="checkbox" accessibilityState={{ checked: agree }} hitSlop={10}>
                    <View style={[styles.checkbox, agree && styles.checkboxChecked]}>
                      {agree && <Ionicons name="checkmark" size={12} color="#FFFFFF" />}
                    </View>
                  </TouchableOpacity>
                  <Text style={styles.agreeText}>
                    I have read and agree to the{' '}
                    <Text style={styles.linkText} onPress={openTerms}>Terms and Conditions</Text> and{' '}
                    <Text style={styles.linkText} onPress={openTerms}>Privacy Policy</Text>
                  </Text>
                </View>
              </Animated.View>

              <LoadingButton
                label="Sign Up"
                loading={isSubmitting}
                onPress={handleSignUp}
                style={[styles.primaryBtn, (!agree || !country) && styles.primaryBtnMuted]}
              />

              <View style={styles.bottomRow}>
                <Text style={styles.bottomText}>Already have an account? </Text>
                <TouchableOpacity onPress={() => router.push('/Screen/Auth/SignInScreen')}>
                  <Text style={styles.bottomLink}>Sign In</Text>
                </TouchableOpacity>
              </View>
            </View>
          </ScrollView>
        </KeyboardAvoidingView>
      </SafeAreaView>

      {/* Country picker */}
      <Sheet visible={countryPickerVisible} onClose={() => setCountryPickerVisible(false)} height={SCREEN_HEIGHT * 0.82}>
        <View style={styles.sheetHeader}>
          <View>
            <Text style={styles.sheetTitle}>Select your country</Text>
            <Text style={styles.sheetSubtitle}>We show prices in your country’s currency</Text>
          </View>
          <TouchableOpacity style={styles.sheetClose} onPress={() => setCountryPickerVisible(false)} accessibilityLabel="Close">
            <Feather name="x" size={18} color="#E2E8F0" />
          </TouchableOpacity>
        </View>
        <View style={styles.searchField}>
          <Feather name="search" size={16} color="#64748B" />
          <TextInput
            style={styles.searchInput}
            placeholder="Search country or currency"
            placeholderTextColor="#64748B"
            value={countryQuery}
            onChangeText={setCountryQuery}
            autoCorrect={false}
          />
          {countryQuery ? (
            <TouchableOpacity onPress={() => setCountryQuery('')} hitSlop={8}><Feather name="x-circle" size={16} color="#64748B" /></TouchableOpacity>
          ) : null}
        </View>
        <FlatList
          data={filteredCountries}
          keyExtractor={(item) => item.code}
          keyboardShouldPersistTaps="handled"
          initialNumToRender={20}
          contentContainerStyle={styles.countryList}
          ListEmptyComponent={<Text style={styles.emptyText}>No country matches “{countryQuery}”.</Text>}
          renderItem={({ item }) => {
            const selected = country?.code === item.code;
            return (
              <TouchableOpacity
                style={[styles.countryRow, selected && styles.countryRowSelected]}
                activeOpacity={0.75}
                onPress={() => { setCountry(item); setCountryPickerVisible(false); }}
              >
                <Text style={styles.countryFlag}>{countryFlag(item.code)}</Text>
                <View style={{ flex: 1 }}>
                  <Text style={styles.countryName} numberOfLines={1}>{item.name}</Text>
                  <Text style={styles.countryCurrency}>{item.currency} · {item.symbol}</Text>
                </View>
                {selected ? <Ionicons name="checkmark-circle" size={20} color="#3B82F6" /> : null}
              </TouchableOpacity>
            );
          }}
        />
      </Sheet>

      {/* Terms and Conditions */}
      <Sheet visible={termsVisible} onClose={() => setTermsVisible(false)} height={SCREEN_HEIGHT * 0.86}>
        <View style={styles.sheetHeader}>
          <View style={styles.termsHeading}>
            <View style={styles.termsIcon}><Feather name="file-text" size={18} color="#93C5FD" /></View>
            <View>
              <Text style={styles.sheetTitle}>Terms and Conditions</Text>
              <Text style={styles.sheetSubtitle}>Last updated {TERMS_UPDATED}</Text>
            </View>
          </View>
          <TouchableOpacity style={styles.sheetClose} onPress={() => setTermsVisible(false)} accessibilityLabel="Close">
            <Feather name="x" size={18} color="#E2E8F0" />
          </TouchableOpacity>
        </View>
        <ScrollView
          style={{ flex: 1 }}
          contentContainerStyle={styles.termsContent}
          showsVerticalScrollIndicator
          scrollEventThrottle={64}
          onScroll={({ nativeEvent }) => {
            const { layoutMeasurement, contentOffset, contentSize } = nativeEvent;
            if (layoutMeasurement.height + contentOffset.y >= contentSize.height - 40) setTermsRead(true);
          }}
          onContentSizeChange={(_, height) => { if (height < SCREEN_HEIGHT * 0.5) setTermsRead(true); }}
        >
          <Text style={styles.termsIntro}>Please read these terms carefully. You need to accept them to create an Apsuni AI account.</Text>
          {TERMS_SECTIONS.map((section) => (
            <View key={section.title} style={styles.termsSection}>
              <Text style={styles.termsTitle}>{section.title}</Text>
              <Text style={styles.termsBody}>{section.body}</Text>
            </View>
          ))}
        </ScrollView>
        <View style={styles.termsFooter}>
          {!termsRead && <Text style={styles.termsScrollHint}>Scroll to the end to accept</Text>}
          <View style={styles.termsActions}>
            <TouchableOpacity style={styles.declineBtn} activeOpacity={0.8} onPress={declineTerms}>
              <Text style={styles.declineText}>Decline</Text>
            </TouchableOpacity>
            <TouchableOpacity style={[styles.acceptBtn, !termsRead && styles.acceptBtnDisabled]} activeOpacity={0.85} disabled={!termsRead} onPress={acceptTerms}>
              <Ionicons name="checkmark" size={16} color="#FFFFFF" />
              <Text style={styles.acceptText}>I agree</Text>
            </TouchableOpacity>
          </View>
        </View>
      </Sheet>
    </View>
  );
}

const styles = StyleSheet.create({
  background: { flex: 1 },
  scrollContent: { paddingHorizontal: 24, paddingBottom: 36 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 8,
  },
  logoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 6,
  },
  logoMark: { alignItems: 'center', justifyContent: 'center' },
  logoImage: { width: 38, height: 38 },
  logoText: {
    fontSize: 22,
    fontWeight: '700',
    color: '#FFFFFF',
    fontStyle: 'italic',
  },
  title: {
    fontSize: 26,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 13,
    color: '#94A3B8',
    textAlign: 'center',
    lineHeight: 19,
    paddingHorizontal: 12,
    marginBottom: 20,
  },
  formCard: {
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    borderRadius: 32,
    padding: 20,
  },
  socialRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 18,
  },
  socialPill: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: 50,
    borderRadius: 25,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    gap: 8,
  },
  socialDisabled: { opacity: 0.4 },
  socialText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  dividerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.12)',
  },
  dividerLabel: {
    fontSize: 12,
    color: '#94A3B8',
    paddingHorizontal: 12,
  },
  labelRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  fieldLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  requiredMark: {
    fontSize: 11,
    color: '#64748B',
    marginBottom: 8,
  },
  fieldHint: {
    fontSize: 11,
    color: '#64748B',
    marginTop: -10,
    marginBottom: 16,
    paddingHorizontal: 6,
  },
  inputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.15)',
    paddingHorizontal: 18,
    height: 52,
    marginBottom: 16,
  },
  fieldIcon: { marginRight: 10 },
  input: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 14,
  },
  placeholderText: { color: '#64748B' },
  flag: { fontSize: 18, marginRight: 10 },
  currencyPill: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 10,
    backgroundColor: 'rgba(59,130,246,0.16)',
    marginHorizontal: 8,
  },
  currencyPillText: { fontSize: 11, fontWeight: '700', color: '#93C5FD' },
  agreeRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    marginBottom: 24,
  },
  checkbox: {
    width: 18,
    height: 18,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 2,
  },
  checkboxChecked: {
    backgroundColor: '#2563EB',
    borderColor: '#2563EB',
  },
  agreeText: {
    flex: 1,
    fontSize: 13,
    color: '#CBD5E1',
    lineHeight: 20,
  },
  linkText: {
    color: '#3B82F6',
    fontWeight: '600',
  },
  primaryBtn: {
    backgroundColor: '#2563EB',
    height: 54,
    borderRadius: 27,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: '#2563EB',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 5,
  },
  primaryBtnMuted: { opacity: 0.6 },
  bottomRow: {
    flexDirection: 'row',
    justifyContent: 'center',
  },
  bottomText: {
    fontSize: 13,
    color: '#94A3B8',
  },
  bottomLink: {
    fontSize: 13,
    color: '#3B82F6',
    fontWeight: '700',
  },

  sheetRoot: { flex: 1, justifyContent: 'flex-end' },
  sheetBackdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(2, 6, 23, 0.72)' },
  sheet: {
    backgroundColor: '#0B1322',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    overflow: 'hidden',
  },
  sheetHandle: { alignSelf: 'center', width: 42, height: 4, borderRadius: 2, backgroundColor: '#2A3A52', marginTop: 10 },
  sheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 12,
  },
  sheetTitle: { fontSize: 18, fontWeight: '800', color: '#FFFFFF' },
  sheetSubtitle: { fontSize: 12, color: '#64748B', marginTop: 3 },
  sheetClose: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(148,163,184,0.12)',
  },
  searchField: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginHorizontal: 20,
    marginBottom: 8,
    paddingHorizontal: 14,
    height: 46,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  searchInput: { flex: 1, color: '#FFFFFF', fontSize: 14 },
  countryList: { paddingHorizontal: 12, paddingBottom: 32 },
  countryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 11,
    paddingHorizontal: 10,
    borderRadius: 14,
  },
  countryRowSelected: { backgroundColor: 'rgba(37,99,235,0.18)' },
  countryFlag: { fontSize: 24 },
  countryName: { fontSize: 14, fontWeight: '600', color: '#F1F5F9' },
  countryCurrency: { fontSize: 11, color: '#64748B', marginTop: 2 },
  emptyText: { color: '#94A3B8', textAlign: 'center', marginTop: 32, fontSize: 13 },

  termsHeading: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1 },
  termsIcon: {
    width: 40,
    height: 40,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(59,130,246,0.14)',
  },
  termsContent: { paddingHorizontal: 20, paddingBottom: 24 },
  termsIntro: {
    fontSize: 13,
    color: '#CBD5E1',
    lineHeight: 20,
    padding: 14,
    borderRadius: 14,
    backgroundColor: 'rgba(59,130,246,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(59,130,246,0.2)',
    marginBottom: 16,
  },
  termsSection: { marginBottom: 16 },
  termsTitle: { fontSize: 14, fontWeight: '700', color: '#FFFFFF', marginBottom: 6 },
  termsBody: { fontSize: 13, color: '#94A3B8', lineHeight: 20 },
  termsFooter: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 28,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,0.08)',
    backgroundColor: '#0B1322',
  },
  termsScrollHint: { fontSize: 11, color: '#64748B', textAlign: 'center', marginBottom: 10 },
  termsActions: { flexDirection: 'row', gap: 12 },
  declineBtn: {
    flex: 1,
    height: 50,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
  },
  declineText: { fontSize: 14, fontWeight: '700', color: '#CBD5E1' },
  acceptBtn: {
    flex: 1.4,
    height: 50,
    borderRadius: 25,
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2563EB',
  },
  acceptBtnDisabled: { opacity: 0.45 },
  acceptText: { fontSize: 14, fontWeight: '800', color: '#FFFFFF' },
});
